name: FaultTrek CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub (replace with your secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t faulttrek:latest -f docker/Dockerfile .

      # Step 5: Run tests (optional)
      - name: Run Python tests
        run: |
          python3 -m pip install -r requirements.txt
          # Add your test commands here, e.g.,
          # pytest tests/

      # Step 6: Push image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag faulttrek:latest your-dockerhub-username/faulttrek:latest
          docker push your-dockerhub-username/faulttrek:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: deployments/faulttrek-deployment.yaml
          images: your-dockerhub-username/faulttrek:latest
          kubectl-version: '1.28.0'
