name: FaultTrek CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKERHUB_USERNAME: ramshenoy7
  IMAGE_NAME: ramshenoy7/faulttrek

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build FaultTrek image for testing
        # This is the corrected command
        run: docker build -t ${{ env.IMAGE_NAME }}:latest -f ./docker/Dockerfile .

      - name: Start services for testing
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Run FaultTrek test suite
        run: docker compose -f docker-compose.ci.yml exec -T faulttrek /bin/sh -c "./run_all_profiles.sh"

      - name: Stop services after testing
        if: always()
        run: docker compose -f docker-compose.ci.yml down

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ${{ env.IMAGE_NAME }}:latest